run:
  tests: false

linters-settings:
  funlen:
    lines: 150
    statements: 80
  goimports:
    local-prefixes: github.com/gardashvs/final-project

linters:
  disable-all: false
  enable-all: false
  disable:
    - typecheck
    - errcheck
    - govet
  enable:
    - unused